try {
    module.exports = practiceSolution;
    module.exports.helperFunction = helperFunction;
  } catch (error) {
    console.log('we caught an error');
  }